// Contenus de la v2. Textes par langue : [fr, en, es, de, nl]
(() => {
const L = ["fr","en","es","de","nl"];
const tr = arr => Object.fromEntries(L.map((l, i) => [l, arr[i]]));

// Citoyens UE, EEE et Suisse (même régime de séjour)
window.EU_CODES = "AT BE BG HR CY CZ DK EE FI FR DE GR HU IE IT LV LT LU MT NL PL PT RO SK SI SE NO IS LI CH".split(" ");

// ---------- CHECKLIST PERSONNALISÉE ----------
// when(p, eu) : p = profil, eu = true / false / null (nationalité inconnue)
window.CHECKLIST = [
 { id:"passport", when:()=>true, t:tr(["Vérifier la validité du passeport ou de la carte d'identité","Check that your passport or ID card is valid","Comprobar la validez del pasaporte o DNI","Gültigkeit von Reisepass oder Ausweis prüfen","Geldigheid van paspoort of identiteitskaart controleren"]) },
 { id:"deregister", when:()=>true, t:tr(["Déclarer votre départ dans votre pays (voir « Par pays d'origine »)","Report your departure in your home country (see “By home country”)","Comunicar tu salida en tu país (ver «Por país de origen»)","Wegzug im Heimatland melden (siehe „Nach Herkunftsland“)","Je vertrek melden in je land (zie ‘Per land van herkomst’)"]) },
 { id:"apostille", when:(p,eu)=>eu!==true, t:tr(["Faire apostiller et traduire vos actes officiels","Get your official documents apostilled and translated","Apostillar y traducir tus documentos oficiales","Offizielle Urkunden apostillieren und übersetzen lassen","Officiële documenten laten apostilleren en vertalen"]) },
 { id:"visa", when:(p,eu)=>eu!==true, t:tr(["Obtenir le visa adapté au consulat avant le départ","Get the right visa from the consulate before leaving","Obtener el visado adecuado en el consulado antes de salir","Passendes Visum vor der Abreise beim Konsulat beantragen","Het juiste visum aanvragen bij het consulaat vóór vertrek"]) },
 { id:"tie", when:(p,eu)=>eu!==true, t:tr(["Demander la TIE dans le mois suivant l'arrivée","Apply for the TIE within a month of arrival","Solicitar la TIE en el mes siguiente a la llegada","TIE innerhalb eines Monats nach Ankunft beantragen","TIE aanvragen binnen een maand na aankomst"]) },
 { id:"euregister", when:(p,eu)=>eu!==false, t:tr(["S'inscrire au registre des citoyens de l'UE (EX-18) si séjour de plus de 3 mois","Register as an EU citizen (EX-18) if staying over 3 months","Inscribirse como ciudadano de la UE (EX-18) si la estancia supera 3 meses","Registrierung als EU-Bürger (EX-18) bei mehr als 3 Monaten","Inschrijven als EU-burger (EX-18) bij verblijf langer dan 3 maanden"]) },
 { id:"nie", when:()=>true, t:tr(["Obtenir votre NIE","Get your NIE","Obtener tu NIE","NIE erhalten","Je NIE verkrijgen"]) },
 { id:"padron", when:()=>true, t:tr(["S'inscrire au padrón de la commune","Register on the town padrón","Empadronarse en el ayuntamiento","Im Padrón der Gemeinde anmelden","Inschrijven in de padrón van de gemeente"]) },
 { id:"bank", when:()=>true, t:tr(["Ouvrir un compte bancaire espagnol","Open a Spanish bank account","Abrir una cuenta bancaria española","Spanisches Bankkonto eröffnen","Een Spaanse bankrekening openen"]) },
 { id:"s1", when:p=>p.work_situation==="retired", t:tr(["Demander le formulaire S1 à votre caisse de pension ou d'assurance maladie","Request the S1 form from your pension or health insurer","Pedir el formulario S1 a tu caja de pensiones o seguro de salud","Formular S1 bei Renten- oder Krankenkasse beantragen","Formulier S1 aanvragen bij je pensioen- of zorgverzekeraar"]) },
 { id:"private_health", when:p=>["planning","nomad","seasonal"].includes(p.status)||["remote","seeking"].includes(p.work_situation), t:tr(["Souscrire une assurance santé privée si vous n'êtes pas couvert(e)","Take out private health insurance if you are not covered","Contratar un seguro médico privado si no tienes cobertura","Private Krankenversicherung abschließen, falls nicht versichert","Een private ziekteverzekering nemen als je niet gedekt bent"]) },
 { id:"nuss", when:p=>["employee","self"].includes(p.work_situation), t:tr(["Obtenir votre numéro de sécurité sociale (NUSS)","Get your social security number (NUSS)","Obtener tu número de la Seguridad Social (NUSS)","Sozialversicherungsnummer (NUSS) erhalten","Je socialezekerheidsnummer (NUSS) verkrijgen"]) },
 { id:"autonomo", when:p=>p.work_situation==="self", t:tr(["S'inscrire comme autónomo (Hacienda et sécurité sociale)","Register as autónomo (tax office and social security)","Darse de alta como autónomo (Hacienda y Seguridad Social)","Als Autónomo anmelden (Finanzamt und Sozialversicherung)","Inschrijven als autónomo (belastingdienst en sociale zekerheid)"]) },
 { id:"jobcentre", when:p=>p.work_situation==="seeking", t:tr(["S'inscrire au service public de l'emploi de votre région","Register with your region's public employment service","Inscribirse en el servicio público de empleo de tu comunidad","Beim öffentlichen Arbeitsamt deiner Region melden","Inschrijven bij de openbare arbeidsdienst van je regio"]) },
 { id:"school", when:p=>(p.children||0)>0, t:tr(["Inscrire les enfants à l'école (demande auprès de la commune ou de la région)","Enrol the children at school (apply through the town or region)","Escolarizar a los hijos (solicitud en el ayuntamiento o la comunidad)","Kinder in der Schule anmelden (über Gemeinde oder Region)","Kinderen inschrijven op school (via gemeente of regio)"]) },
 { id:"pet", when:p=>p.pets, t:tr(["Animal : puce électronique, passeport européen et vaccin antirabique à jour","Pet: microchip, EU pet passport and up-to-date rabies vaccine","Mascota: microchip, pasaporte europeo y vacuna antirrábica al día","Haustier: Mikrochip, EU-Heimtierausweis und gültige Tollwutimpfung","Huisdier: chip, Europees dierenpaspoort en geldige rabiësvaccinatie"]) },
 { id:"rent_docs", when:p=>["searching","renting"].includes(p.housing)||!p.housing, t:tr(["Préparer un dossier de location : NIE, justificatifs de revenus, contrat de travail ou pension","Prepare a rental file: NIE, proof of income, work contract or pension","Preparar el dossier de alquiler: NIE, justificantes de ingresos, contrato o pensión","Mietunterlagen vorbereiten: NIE, Einkommensnachweise, Arbeitsvertrag oder Rente","Een huurdossier voorbereiden: NIE, inkomensbewijzen, arbeidscontract of pensioen"]) },
 { id:"tax", when:()=>true, t:tr(["Vérifier votre résidence fiscale et prévenir le fisc de votre pays","Check your tax residency and inform your home tax office","Comprobar tu residencia fiscal e informar a Hacienda de tu país","Steuerliche Ansässigkeit prüfen und heimisches Finanzamt informieren","Je fiscale woonplaats nagaan en de belastingdienst van je land inlichten"]) },
 { id:"licence", when:(p,eu)=>eu!==true, t:tr(["Échanger votre permis de conduire dans les délais","Exchange your driving licence within the deadline","Canjear tu permiso de conducir dentro del plazo","Führerschein fristgerecht umtauschen","Je rijbewijs binnen de termijn omwisselen"]) }
];

// ---------- GUIDES PAR PAYS D'ORIGINE ----------
window.COUNTRY_GUIDES = [
 { code:"BE", links:[["Affaires étrangères (Belges à l'étranger)","https://diplomatie.belgium.be/"],["Service fédéral des Pensions","https://www.sfpd.fgov.be/"]],
   p:tr([
    ["Déclarez votre départ à votre commune avant de partir : vous recevez un certificat de changement de résidence (modèle 8).","Pensionnés : demandez le formulaire S1 à votre mutualité pour être soigné(e) en Espagne à charge de la Belgique.","Inscrivez-vous au registre consulaire de l'ambassade ou d'un consulat belge en Espagne (passeport, élections, documents).","Impôts : l'année du départ, déclarez vos revenus en Belgique jusqu'à la date de départ. Certains revenus belges, comme les pensions du secteur public, peuvent rester imposables en Belgique selon la convention."],
    ["Report your departure to your municipality before leaving: you will receive a change-of-residence certificate (model 8).","Pensioners: ask your health fund (mutualité/ziekenfonds) for the S1 form to be treated in Spain at Belgium's expense.","Register with the consular register of the Belgian embassy or a consulate in Spain (passport, elections, documents).","Taxes: in the year you leave, declare your income in Belgium up to your departure date. Some Belgian income, such as public-sector pensions, may remain taxable in Belgium under the treaty."],
    ["Declara tu salida en tu municipio antes de irte: recibirás un certificado de cambio de residencia (modelo 8).","Pensionistas: pide el formulario S1 a tu mutualidad para recibir asistencia en España a cargo de Bélgica.","Inscríbete en el registro consular de la embajada o de un consulado belga en España (pasaporte, elecciones, documentos).","Impuestos: el año de la salida declaras en Bélgica tus rentas hasta la fecha de partida. Algunas rentas belgas, como las pensiones públicas, pueden seguir tributando en Bélgica según el convenio."],
    ["Melde deinen Wegzug vor der Abreise bei deiner Gemeinde: Du erhältst eine Bescheinigung über den Wohnsitzwechsel (Modell 8).","Rentner: Beantrage bei deiner Krankenkasse (Mutualität) das Formular S1, um in Spanien auf Kosten Belgiens behandelt zu werden.","Trage dich im Konsularregister der belgischen Botschaft oder eines Konsulats in Spanien ein (Pass, Wahlen, Dokumente).","Steuern: Im Jahr des Wegzugs erklärst du dein Einkommen in Belgien bis zum Wegzugsdatum. Manche belgischen Einkünfte, etwa Beamtenpensionen, können laut Abkommen in Belgien steuerpflichtig bleiben."],
    ["Meld je vertrek bij je gemeente vóór je vertrekt: je krijgt een attest van adreswijziging (model 8).","Gepensioneerden: vraag bij je ziekenfonds het formulier S1 aan om in Spanje verzorgd te worden op kosten van België.","Schrijf je in het consulaire register in bij de Belgische ambassade of een consulaat in Spanje (paspoort, verkiezingen, documenten).","Belastingen: in het jaar van vertrek geef je je inkomsten in België aan tot de vertrekdatum. Sommige Belgische inkomsten, zoals overheidspensioenen, kunnen volgens het verdrag in België belastbaar blijven."]
   ]) },
 { code:"FR", links:[["Service-Public (vivre à l'étranger)","https://www.service-public.fr/"],["Impôts","https://www.impots.gouv.fr/"],["Ameli","https://www.ameli.fr/"]],
   p:tr([
    ["Pas de radiation en mairie : signalez votre nouvelle adresse aux impôts, à votre caisse de retraite, à votre banque et à vos assurances.","Retraités : demandez le formulaire S1 à votre caisse d'assurance maladie pour être soigné(e) en Espagne à charge de la France.","L'inscription au registre des Français établis hors de France (consulat) est facultative mais conseillée.","Impôts : l'année du départ, déclarez vos revenus en indiquant la date de départ. Certains revenus de source française restent imposables en France. Chômage : le formulaire U2 permet de toucher vos allocations pendant votre recherche en Espagne, pour une durée limitée."],
    ["No deregistration at the town hall: give your new address to the tax office, your pension fund, your bank and your insurers.","Pensioners: ask your health insurance fund for the S1 form to be treated in Spain at France's expense.","Registering with the register of French nationals abroad (consulate) is optional but recommended.","Taxes: in the year you leave, declare your income and state your departure date. Some French-source income stays taxable in France. Unemployment: form U2 lets you keep benefits for a limited time while job hunting in Spain."],
    ["No hay baja en el ayuntamiento: comunica tu nueva dirección a Hacienda, a tu caja de pensiones, a tu banco y a tus seguros.","Jubilados: pide el formulario S1 a tu caja del seguro de enfermedad para recibir asistencia en España a cargo de Francia.","La inscripción en el registro de franceses en el extranjero (consulado) es opcional pero recomendable.","Impuestos: el año de salida declaras tus rentas indicando la fecha de partida. Algunas rentas de fuente francesa siguen tributando en Francia. Desempleo: el formulario U2 permite cobrar la prestación durante un tiempo limitado mientras buscas trabajo en España."],
    ["Keine Abmeldung im Rathaus: Teile Finanzamt, Rentenkasse, Bank und Versicherungen deine neue Adresse mit.","Rentner: Beantrage bei deiner Krankenkasse das Formular S1, um in Spanien auf Kosten Frankreichs behandelt zu werden.","Die Eintragung ins Register der Franzosen im Ausland (Konsulat) ist freiwillig, aber empfehlenswert.","Steuern: Im Jahr des Wegzugs gibst du dein Einkommen mit dem Wegzugsdatum an. Manche Einkünfte aus Frankreich bleiben dort steuerpflichtig. Arbeitslosigkeit: Mit dem Formular U2 kannst du das Arbeitslosengeld für begrenzte Zeit bei der Jobsuche in Spanien behalten."],
    ["Geen uitschrijving bij het gemeentehuis: geef je nieuwe adres door aan de belastingdienst, je pensioenkas, je bank en je verzekeraars.","Gepensioneerden: vraag bij je ziekenfonds het formulier S1 aan om in Spanje verzorgd te worden op kosten van Frankrijk.","Inschrijving in het register van Fransen in het buitenland (consulaat) is optioneel maar aangeraden.","Belastingen: in het jaar van vertrek geef je je inkomsten aan met de vertrekdatum. Sommige inkomsten uit Frankrijk blijven daar belastbaar. Werkloosheid: met formulier U2 behoud je je uitkering een beperkte tijd terwijl je in Spanje werk zoekt."]
   ]) },
 { code:"NL", links:[["Rijksoverheid (emigreren)","https://www.rijksoverheid.nl/"],["SVB","https://www.svb.nl/"],["Belastingdienst","https://www.belastingdienst.nl/"]],
   p:tr([
    ["Désinscrivez-vous de votre commune (BRP) si vous partez plus de 8 mois : votre assurance santé néerlandaise prend alors fin.","Pensionnés : la couverture santé en Espagne passe en général par le formulaire S1, via le CAK (verdragsregeling).","AOW : communiquez votre nouvelle adresse à la SVB. Vous ne cotisez plus pour l'AOW en vivant à l'étranger, une assurance volontaire est possible.","Impôts : l'année de l'émigration, remplissez la déclaration « M » de la Belastingdienst."],
    ["Deregister from your municipality (BRP) if you leave for more than 8 months: your Dutch health insurance then ends.","Pensioners: healthcare in Spain usually goes through the S1 form, via the CAK (treaty arrangement).","AOW: give your new address to the SVB. You stop building AOW while living abroad; voluntary insurance is possible.","Taxes: in the year you emigrate, file the Belastingdienst's “M” return."],
    ["Date de baja en tu municipio (BRP) si te vas más de 8 meses: tu seguro de salud neerlandés termina entonces.","Pensionistas: la cobertura sanitaria en España suele pasar por el formulario S1, a través del CAK (verdragsregeling).","AOW: comunica tu nueva dirección a la SVB. Dejas de cotizar para la AOW al vivir fuera; existe un seguro voluntario.","Impuestos: el año de emigración, presenta la declaración «M» de la Belastingdienst."],
    ["Melde dich bei deiner Gemeinde ab (BRP), wenn du länger als 8 Monate weg bist: Deine niederländische Krankenversicherung endet dann.","Rentner: Die Versorgung in Spanien läuft meist über das Formular S1, über das CAK (verdragsregeling).","AOW: Teile der SVB deine neue Adresse mit. Im Ausland baust du keine AOW mehr auf, eine freiwillige Versicherung ist möglich.","Steuern: Reiche im Auswanderungsjahr die „M“-Erklärung der Belastingdienst ein."],
    ["Schrijf je uit bij je gemeente (BRP) als je langer dan 8 maanden vertrekt: je Nederlandse zorgverzekering stopt dan.","Gepensioneerden: zorg in Spanje loopt meestal via formulier S1, via het CAK (verdragsregeling).","AOW: geef je nieuwe adres door aan de SVB. In het buitenland bouw je geen AOW meer op; vrijwillig verzekeren kan.","Belastingen: vul in het jaar van emigratie de M-aangifte van de Belastingdienst in."]
   ]) },
 { code:"DE", links:[["Auswärtiges Amt","https://www.auswaertiges-amt.de/"],["Deutsche Rentenversicherung","https://www.deutsche-rentenversicherung.de/"]],
   p:tr([
    ["Faites votre Abmeldung au Bürgeramt dans les deux semaines suivant le départ.","Retraités : demandez le formulaire S1 à votre Krankenkasse pour être soigné(e) en Espagne.","Deutsche Rentenversicherung : communiquez votre nouvelle adresse et votre compte bancaire ; la pension est versée dans l'UE.","Impôts : l'assujettissement illimité prend fin avec le départ, mais les pensions allemandes peuvent rester imposables en Allemagne (centre des impôts de Neubrandenburg pour les retraités à l'étranger). Chômage : formulaire U2 auprès de l'Agentur für Arbeit."],
    ["Do your Abmeldung at the Bürgeramt within two weeks of leaving.","Pensioners: ask your Krankenkasse for the S1 form to be treated in Spain.","Deutsche Rentenversicherung: give your new address and bank account; the pension is paid anywhere in the EU.","Taxes: unlimited tax liability ends when you leave, but German pensions may remain taxable in Germany (Neubrandenburg tax office for pensioners abroad). Unemployment: form U2 from the Agentur für Arbeit."],
    ["Haz la Abmeldung en el Bürgeramt en las dos semanas siguientes a la salida.","Jubilados: pide el formulario S1 a tu Krankenkasse para recibir asistencia en España.","Deutsche Rentenversicherung: comunica tu nueva dirección y cuenta bancaria; la pensión se paga en toda la UE.","Impuestos: la obligación ilimitada termina con la salida, pero las pensiones alemanas pueden seguir tributando en Alemania (oficina de Neubrandenburg para jubilados en el extranjero). Desempleo: formulario U2 en la Agentur für Arbeit."],
    ["Melde dich innerhalb von zwei Wochen nach dem Auszug beim Bürgeramt ab.","Rentner: Beantrage bei deiner Krankenkasse das Formular S1 für die Behandlung in Spanien.","Deutsche Rentenversicherung: Neue Adresse und Bankverbindung melden; die Rente wird überall in der EU gezahlt.","Steuern: Die unbeschränkte Steuerpflicht endet mit dem Wegzug, deutsche Renten können aber in Deutschland steuerpflichtig bleiben (Finanzamt Neubrandenburg für Rentner im Ausland). Arbeitslosigkeit: Formular U2 bei der Agentur für Arbeit."],
    ["Meld je binnen twee weken na vertrek af bij het Bürgeramt.","Gepensioneerden: vraag bij je Krankenkasse het formulier S1 aan voor zorg in Spanje.","Deutsche Rentenversicherung: geef je nieuwe adres en bankrekening door; het pensioen wordt overal in de EU uitbetaald.","Belastingen: de onbeperkte belastingplicht eindigt met het vertrek, maar Duitse pensioenen kunnen in Duitsland belastbaar blijven (belastingkantoor Neubrandenburg voor gepensioneerden in het buitenland). Werkloosheid: formulier U2 bij de Agentur für Arbeit."]
   ]) },
 { code:"GB", links:[["GOV.UK — Living in Spain","https://www.gov.uk/guidance/living-in-spain"],["GOV.UK","https://www.gov.uk/"]],
   p:tr([
    ["Depuis le Brexit, un visa est nécessaire pour vivre en Espagne, sauf pour les personnes déjà résidentes avant 2021 (accord de retrait, carte TIE).","Informez HMRC de votre départ (formulaire P85) et l'International Pension Centre de votre nouvelle adresse : la State Pension peut être versée en Espagne et y est revalorisée.","Les retraités britanniques peuvent obtenir un S1 pour être soignés en Espagne (NHS Overseas Healthcare Services).","Permis : un accord Royaume-Uni–Espagne permet l'échange du permis britannique, à faire dans les 6 mois suivant l'obtention de la résidence."],
    ["Since Brexit you need a visa to live in Spain, unless you were already resident before 2021 (Withdrawal Agreement, TIE card).","Tell HMRC you are leaving (form P85) and the International Pension Centre your new address: the State Pension can be paid in Spain and is uprated there.","UK pensioners can get an S1 for healthcare in Spain (NHS Overseas Healthcare Services).","Licence: a UK–Spain agreement allows you to exchange your UK licence, within 6 months of becoming resident."],
    ["Desde el Brexit se necesita visado para vivir en España, salvo quienes ya residían antes de 2021 (Acuerdo de Retirada, TIE).","Informa a HMRC de tu salida (formulario P85) y al International Pension Centre de tu nueva dirección: la State Pension se puede cobrar en España y se revaloriza.","Los pensionistas británicos pueden obtener un S1 para recibir asistencia en España (NHS Overseas Healthcare Services).","Permiso: un acuerdo Reino Unido–España permite canjear el permiso británico en los 6 meses siguientes a obtener la residencia."],
    ["Seit dem Brexit brauchst du ein Visum für Spanien, außer du warst schon vor 2021 ansässig (Austrittsabkommen, TIE).","Informiere HMRC über den Wegzug (Formular P85) und das International Pension Centre über die neue Adresse: Die State Pension wird in Spanien gezahlt und dort angepasst.","Britische Rentner können ein S1 für die Versorgung in Spanien erhalten (NHS Overseas Healthcare Services).","Führerschein: Ein Abkommen zwischen UK und Spanien erlaubt den Umtausch innerhalb von 6 Monaten nach Erhalt des Wohnsitzes."],
    ["Sinds de Brexit heb je een visum nodig om in Spanje te wonen, tenzij je er al vóór 2021 woonde (terugtrekkingsakkoord, TIE).","Meld je vertrek aan HMRC (formulier P85) en je nieuwe adres aan het International Pension Centre: de State Pension kan in Spanje uitbetaald worden en wordt er geïndexeerd.","Britse gepensioneerden kunnen een S1 krijgen voor zorg in Spanje (NHS Overseas Healthcare Services).","Rijbewijs: een akkoord tussen het VK en Spanje laat omwisseling toe binnen 6 maanden na het verkrijgen van de verblijfsvergunning."]
   ]) }
];

// ---------- ÉCHÉANCES ----------
// Annuelles : [mois (1-12), jour]. Personnelles : jours après la date d'arrivée, et pour qui.
window.DEADLINES_YEARLY = [
 { id:"m720", md:[3,31], t:tr(["Modèle 720 (biens à l'étranger de plus de 50 000 €) : date limite","Form 720 (assets abroad over €50,000): deadline","Modelo 720 (bienes en el extranjero de más de 50 000 €): plazo","Modelo 720 (Auslandsvermögen über 50.000 €): Frist","Modelo 720 (buitenlandse bezittingen boven 50.000 €): deadline"]) },
 { id:"renta", md:[6,30], t:tr(["Déclaration de revenus (IRPF) : la campagne se termine généralement fin juin","Income tax return (IRPF): the campaign usually ends late June","Declaración de la renta (IRPF): la campaña suele terminar a finales de junio","Einkommensteuererklärung (IRPF): Die Kampagne endet meist Ende Juni","Aangifte inkomstenbelasting (IRPF): de campagne eindigt meestal eind juni"]) }
];
window.DEADLINES_PERSONAL = [
 { id:"tie", days:30, who:eu=>eu!==true, t:tr(["Demander la TIE (1 mois après l'arrivée)","Apply for the TIE (1 month after arrival)","Solicitar la TIE (1 mes tras la llegada)","TIE beantragen (1 Monat nach Ankunft)","TIE aanvragen (1 maand na aankomst)"]) },
 { id:"eureg", days:90, who:eu=>eu!==false, t:tr(["Registre des citoyens de l'UE (au-delà de 3 mois de séjour)","EU citizen registration (after 3 months' stay)","Registro de ciudadano de la UE (a partir de 3 meses)","Registrierung als EU-Bürger (nach 3 Monaten)","Registratie als EU-burger (na 3 maanden verblijf)"]) },
 { id:"tax183", days:183, who:()=>true, t:tr(["183 jours en Espagne : vous devenez en principe résident(e) fiscal(e)","183 days in Spain: you generally become tax resident","183 días en España: en general pasas a ser residente fiscal","183 Tage in Spanien: Du wirst in der Regel steuerlich ansässig","183 dagen in Spanje: je wordt in principe fiscaal inwoner"]) },
 { id:"year1", days:365, who:()=>true, t:tr(["1 an en Espagne : faites le point sur vos impôts, votre assurance et vos papiers","1 year in Spain: review your taxes, insurance and papers","1 año en España: revisa tus impuestos, tu seguro y tus papeles","1 Jahr in Spanien: Steuern, Versicherung und Papiere überprüfen","1 jaar in Spanje: kijk je belastingen, verzekering en papieren na"]) },
 { id:"permanent", days:1826, who:()=>true, t:tr(["5 ans de résidence légale : résidence permanente (UE) ou de longue durée (hors UE) possible","5 years of legal residence: permanent (EU) or long-term (non-EU) residence possible","5 años de residencia legal: residencia permanente (UE) o de larga duración (fuera de la UE)","5 Jahre legaler Aufenthalt: Daueraufenthalt (EU) oder langfristiger Aufenthalt (Nicht-EU) möglich","5 jaar legaal verblijf: duurzaam verblijf (EU) of langdurig ingezetene (niet-EU) mogelijk"]) },
 { id:"nationality", days:3652, who:()=>true, t:tr(["10 ans de résidence : demande de nationalité espagnole possible en règle générale (délais plus courts pour certaines nationalités)","10 years of residence: Spanish nationality can generally be requested (shorter for some nationalities)","10 años de residencia: en general se puede solicitar la nacionalidad española (plazos más cortos para algunas nacionalidades)","10 Jahre Aufenthalt: Einbürgerung in Spanien in der Regel möglich (kürzer für manche Staatsangehörigkeiten)","10 jaar verblijf: Spaanse nationaliteit in principe aan te vragen (korter voor sommige nationaliteiten)"]) },
 { id:"licence", days:180, who:eu=>eu!==true, t:tr(["Échange du permis de conduire (environ 6 mois après la résidence)","Driving licence exchange (about 6 months after residency)","Canje del permiso de conducir (unos 6 meses tras la residencia)","Führerscheinumtausch (etwa 6 Monate nach Wohnsitznahme)","Omwisseling rijbewijs (ongeveer 6 maanden na verblijf)"]) }
];

// ---------- LEXIQUE ----------
window.LEXICON = [
 ["NIE", tr(["Numéro d'identification d'étranger, demandé pour presque toutes les démarches.","Foreigner's identification number, needed for almost every procedure.","Número de Identidad de Extranjero, necesario para casi todos los trámites.","Ausländer-Identifikationsnummer, für fast alle Behördengänge nötig.","Identificatienummer voor buitenlanders, nodig voor bijna alle formaliteiten."])],
 ["TIE", tr(["Carte de séjour physique des ressortissants hors UE.","Physical residence card for non-EU nationals.","Tarjeta física de residencia para ciudadanos de fuera de la UE.","Aufenthaltskarte für Nicht-EU-Bürger.","Verblijfskaart voor niet-EU-burgers."])],
 ["Certificado de registro", tr(["Certificat vert d'inscription des citoyens de l'UE, avec le NIE.","Green registration certificate for EU citizens, showing the NIE.","Certificado verde de registro de ciudadano de la UE, con el NIE.","Grüne Registrierungsbescheinigung für EU-Bürger, mit der NIE.","Groen inschrijvingscertificaat voor EU-burgers, met het NIE."])],
 ["Padrón / Empadronamiento", tr(["Inscription au registre des habitants de la commune.","Registration on the town's register of residents.","Inscripción en el registro de habitantes del municipio.","Anmeldung im Einwohnerregister der Gemeinde.","Inschrijving in het bevolkingsregister van de gemeente."])],
 ["Cita previa", tr(["Rendez-vous obligatoire, pris en ligne, pour la plupart des administrations.","Compulsory appointment, booked online, for most public offices.","Cita obligatoria, pedida por internet, en la mayoría de administraciones.","Pflichttermin, online gebucht, bei den meisten Behörden.","Verplichte afspraak, online te maken, bij de meeste overheidsdiensten."])],
 ["Gestoría / Gestor", tr(["Cabinet qui gère vos démarches administratives et fiscales contre rémunération.","Office that handles your paperwork and taxes for a fee.","Despacho que gestiona tus trámites y tus impuestos a cambio de honorarios.","Büro, das gegen Gebühr Behördengänge und Steuern erledigt.","Kantoor dat tegen betaling je formaliteiten en belastingen regelt."])],
 ["Hacienda / Agencia Tributaria", tr(["L'administration fiscale espagnole.","The Spanish tax authority.","La administración tributaria española.","Die spanische Steuerbehörde.","De Spaanse belastingdienst."])],
 ["IRPF / Renta", tr(["Impôt sur le revenu et déclaration annuelle.","Income tax and the annual return.","Impuesto sobre la renta y declaración anual.","Einkommensteuer und jährliche Erklärung.","Inkomstenbelasting en jaarlijkse aangifte."])],
 ["IBI", tr(["Taxe foncière annuelle payée par le propriétaire.","Annual property tax paid by the owner.","Impuesto anual sobre bienes inmuebles, a cargo del propietario.","Jährliche Grundsteuer des Eigentümers.","Jaarlijkse onroerendgoedbelasting voor de eigenaar."])],
 ["ITP", tr(["Taxe sur l'achat d'un logement ancien, variable selon la région.","Tax on buying a resale home, varies by region.","Impuesto al comprar vivienda de segunda mano, varía según la comunidad.","Steuer beim Kauf einer Bestandsimmobilie, je nach Region unterschiedlich.","Belasting bij aankoop van een bestaande woning, verschilt per regio."])],
 ["Nota simple", tr(["Extrait du registre de la propriété : propriétaire, dettes et charges du bien.","Land registry extract: owner, debts and charges on the property.","Extracto del Registro de la Propiedad: titular, cargas y deudas del inmueble.","Grundbuchauszug: Eigentümer, Schulden und Belastungen der Immobilie.","Uittreksel uit het eigendomsregister: eigenaar, schulden en lasten van het pand."])],
 ["Fianza", tr(["Caution versée à la signature d'un bail.","Deposit paid when signing a lease.","Depósito que se paga al firmar el contrato de alquiler.","Kaution bei Unterzeichnung des Mietvertrags.","Waarborg betaald bij het tekenen van een huurcontract."])],
 ["Comunidad de propietarios", tr(["Copropriété et ses charges mensuelles.","Owners' association and its monthly fees.","Comunidad de vecinos y sus cuotas mensuales.","Eigentümergemeinschaft und ihr monatliches Hausgeld.","Vereniging van eigenaars en de maandelijkse kosten."])],
 ["Autónomo", tr(["Travailleur indépendant inscrit au régime spécial (RETA).","Self-employed worker registered with the special scheme (RETA).","Trabajador por cuenta propia dado de alta en el RETA.","Selbstständiger, beim Sonderregime RETA angemeldet.","Zelfstandige ingeschreven in het speciale stelsel (RETA)."])],
 ["NUSS", tr(["Numéro de sécurité sociale.","Social security number.","Número de afiliación a la Seguridad Social.","Sozialversicherungsnummer.","Socialezekerheidsnummer."])],
 ["Tarjeta sanitaria", tr(["Carte d'accès aux soins publics, délivrée par la région.","Card giving access to public healthcare, issued by the region.","Tarjeta de acceso a la sanidad pública, emitida por la comunidad.","Karte für die öffentliche Gesundheitsversorgung, von der Region ausgestellt.","Kaart voor toegang tot de openbare zorg, uitgereikt door de regio."])],
 ["Apostille", tr(["Tampon officiel qui authentifie un document étranger.","Official stamp that authenticates a foreign document.","Sello oficial que legaliza un documento extranjero.","Amtlicher Stempel, der eine ausländische Urkunde beglaubigt.","Officiële stempel die een buitenlands document legaliseert."])]
];

// ---------- CHARTE ----------
window.CHARTER = tr([
 ["Respectez chaque membre, quelles que soient son origine, sa langue ou sa situation.","Pas de démarchage commercial ni de publicité non sollicitée, en public comme en privé.","Ne demandez jamais d'argent et ne partagez pas vos papiers d'identité ou coordonnées bancaires.","Les conseils partagés sont des expériences personnelles, pas des avis juridiques : vérifiez auprès des sources officielles.","Pour les rencontres, choisissez un lieu public, prévenez un proche et faites confiance à votre ressenti.","Signalez tout comportement inapproprié : nous examinons chaque signalement."],
 ["Respect every member, whatever their origin, language or situation.","No sales pitches or unsolicited advertising, in public or in private.","Never ask for money, and never share ID documents or bank details.","Advice shared here is personal experience, not legal advice: check official sources.","For meetups, choose a public place, tell someone close to you and trust your instincts.","Report any inappropriate behaviour: we review every report."],
 ["Respeta a cada miembro, sea cual sea su origen, idioma o situación.","Nada de captación comercial ni publicidad no solicitada, en público ni en privado.","No pidas nunca dinero ni compartas documentos de identidad o datos bancarios.","Los consejos compartidos son experiencias personales, no asesoramiento jurídico: consulta las fuentes oficiales.","Para quedar, elige un lugar público, avisa a alguien de confianza y fíate de tu intuición.","Denuncia cualquier comportamiento inapropiado: revisamos cada denuncia."],
 ["Respektiere jedes Mitglied, unabhängig von Herkunft, Sprache oder Situation.","Keine Verkaufsangebote oder unerwünschte Werbung, weder öffentlich noch privat.","Bitte nie um Geld und teile keine Ausweisdokumente oder Bankdaten.","Geteilte Ratschläge sind persönliche Erfahrungen, keine Rechtsberatung: Prüfe offizielle Quellen.","Wähle für Treffen einen öffentlichen Ort, sag einer vertrauten Person Bescheid und hör auf dein Gefühl.","Melde unangemessenes Verhalten: Wir prüfen jede Meldung."],
 ["Respecteer elk lid, ongeacht afkomst, taal of situatie.","Geen verkooppraatjes of ongevraagde reclame, niet in het openbaar en niet privé.","Vraag nooit om geld en deel geen identiteitsdocumenten of bankgegevens.","Gedeeld advies is persoonlijke ervaring, geen juridisch advies: controleer officiële bronnen.","Kies voor ontmoetingen een openbare plek, verwittig iemand in je omgeving en vertrouw op je gevoel.","Meld ongepast gedrag: we bekijken elke melding."]
]);
})();
